# Deployment Target
platform :ios, '10.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!

# Cartage support
install! 'cocoapods',
    :share_schemes_for_development_pods => true


target 'Animators_Example' do
    pod 'Animators', :path => '../'
    pod 'APExtensions'
    pod 'BaseClasses'

    target 'Animators_Tests' do
        inherit! :search_paths

        pod 'Quick'
        pod 'Nimble'
        pod 'Nimble-Snapshots'
    end
end


post_install do |installer|
    # Add podInstall.command and podUpdate.command shell scripts to Pods project
    pods_project = installer.pods_project
    pods_project.new_file "../podInstall.command"
    pods_project.new_file "../podUpdate.command"
end
